#Non Graded Challenge 4 - Linear Algebra - Matrix
##Identity
Nama Garvin, student hacktiv8 Batch RMT-20

##Soal
Buatlah Tensor dibawah ini dengan Python:

 
Lakukan perkalian terhadap matrix berikut:

 
 
Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

 


##Jawab

###Soal 1
Buatlah Tensor

In [1]:
import numpy as np

In [2]:
soal_1 = np.array([
    [[23,50],[7,12]],
    [[75,21],[57,12]],
    [[57,67],[99,43]],
    [[87,26],[18,84]],
])

soal_1

array([[[23, 50],
        [ 7, 12]],

       [[75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43]],

       [[87, 26],
        [18, 84]]])

###Soal 2
Lakukan perkalian

In [20]:
a = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])
b = np.array([17,22,19])

print('Vektor A = \n',a)
print('')
print('Vektor B = \n',b)

Vektor A = 
 [[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

Vektor B = 
 [17 22 19]


In [22]:
c = a @ b
print('Perkalian a dan b = \n', c)

Perkalian a dan b = 
 [1852 2454 4305]


###Soal 3
Transpose, hitung determinan, dan inverse

In [23]:
d = np.array([
    [23,50,29],
    [7,12,109],
    [57,67,98]
])
d

array([[ 23,  50,  29],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [28]:
# Transpose
e = d.T
print('Transpose = \n ', e)

Transpose = 
  [[ 23   7  57]
 [ 50  12  67]
 [ 29 109  98]]


In [29]:
# Determinan
f = np.linalg.det(d)
print('Determinan = ', f)

Determinan =  129193.99999999999


In [31]:
# Inverse
g = np.linalg.inv(d)
print('Inverse = \n', g)

Inverse = 
 [[-0.0474248  -0.02288806  0.039491  ]
 [ 0.04278062  0.00465192 -0.01783365]
 [-0.00166416  0.01013205 -0.00057278]]
